PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX swrl: <http://www.w3.org/2003/11/swrl#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX bfo: <http://purl.obolibrary.org/obo/BFO_>
PREFIX ro: <http://purl.obolibrary.org/obo/RO_>
PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies/>

# Note: filters only work when all referenced terms and their axioms are succesfully imported
# Note: this should be used after materializing all mappings, however this query does not necessarily show all mappings
SELECT ?targetTermLabel ?predicate ?sourceTermLabel
WHERE {
    VALUES ?termType { owl:Class owl:ObjectProperty  } .
    ?targetTerm a ?termType .

    FILTER ( 
      STRSTARTS(STR(?targetTerm), STR(prov:))
      &&
      ( STRSTARTS(STR(?sourceTerm), STR(bfo:)) || STRSTARTS(STR(?sourceTerm), STR(ro:)) || STRSTARTS(STR(?sourceTerm), STR(cco:)) )
    )

    ?targetTerm ?predicate ?sourceTerm . 

    OPTIONAL {
      ?targetTerm rdfs:label ?targetTermLabel .
    }
    OPTIONAL {
      ?sourceTerm rdfs:label ?sourceTermLabel .
    }
    # OPTIONAL {
    #   ?predicate rdfs:label ?predicateLabel .
    # }
} ORDER BY ?predicate ?targetTerm