PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX cco: <http://www.ontologyrepository.com/CommonCoreOntologies>

SELECT DISTINCT ?targetProperty ?superDomainLabel ?domainLabel ?targetPropertyLabel ?rangeLabel ?superRangeLabel  ?otherProperty ?otherDomainLabel ?otherPropertyLabel ?otherRangeLabel
WHERE {
  ?targetProperty a owl:ObjectProperty .
  ?targetProperty rdfs:label ?targetPropertyLabel .

  ?targetProperty rdfs:domain ?domain .
  ?targetProperty rdfs:range ?range .
  ?domain rdfs:label ?domainLabel .
  ?range rdfs:label ?rangeLabel .
  
  ?domain rdfs:subClassOf* ?superDomain .
  ?range rdfs:subClassOf* ?superRange .
  ?superDomain rdfs:label ?superDomainLabel .
  ?superRange rdfs:label ?superRangeLabel .

  ?otherProperty a owl:ObjectProperty .
  ?otherProperty rdfs:label ?otherPropertyLabel .

  ?otherProperty rdfs:domain ?otherDomain .
  ?otherProperty rdfs:range ?otherRange .
  ?otherDomain rdfs:label ?otherDomainLabel .
  ?otherRange rdfs:label ?otherRangeLabel .

  # ?targetOntology a owl:Ontology .
  # FILTER( STRSTARTS(str(?targetProperty), str(?targetOntology))) .
  BIND(prov: AS ?targetOntology) . 

  # find alignments to a specific ontology
  BIND(cco: AS ?otherOntology) . 
  FILTER(STRSTARTS(str(?targetProperty), str(?targetOntology)) && STRSTARTS(str(?otherProperty), str(?otherOntology)) && (?superDomain = ?otherDomain || ?domain = ?otherdomain) && (?superRange = ?otherRange || ?range = ?otherRange)) .
  
  # find alignments to ontology except the target one
  # FILTER(STRSTARTS(str(?targetProperty), str(?targetOntology)) && !STRSTARTS(str(?otherProperty), str(?targetOntology)) && (?superDomain = ?otherDomain || ?domain = ?otherdomain) && (?superRange = ?otherRange || ?range = ?otherRange)) .

  # FILTER( !STRSTARTS(str(?otherProperty), str(?targetOntology))) .
}
ORDER BY ?targetProperty ?superDomainLabel

# Notes: Prov:entity complex subclass axiom prevents us from finding it as a matching domain